SecRule REMOTE_ADDR "@ipMatch 10.0.2.137" \
 "id:100001,phase:1,deny,status:403,msg:'Detect IP'"

SecRule ARGS "facebook" "id:100002, phase:1, log, deny, status:403, msg:'Detect Facebook'"

SecRule REQUEST_HEADERS:Content-Length "@gt 1048576" "id:100003, phase:1, log, deny, status:413, msg:'File upload size exceeded 1MB'"
